name: GitHub Contribution Snake

on:
  schedule:
    - cron: '* * * * *'  # daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: joelday/github-contribution-grid-snake@v2
        with:
          username: jyee0719   # replace with your GitHub username
          output: public/github-contribution-grid-snake.svg

      - name: Commit & Push SVG
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add public/github-contribution-grid-snake.svg
          git commit -m "Update contribution snake" || echo "No changes"
          git push
